name: define_env
on:
    workflow_call:
        outputs: 
            ENV:
                description: 'environnement'
                value: ${{ jobs.define_env_variable.outputs.ENV }}

jobs:
    define_env_variable:
      runs-on: ubuntu-latest
      name: environment
      outputs:
        ENV: ${{ steps.env_step.outputs.ENV }}

      steps:
        - name: Déterminer environnement
          id: env_step
          run: |
            BRANCH_NAME=""
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
            else
              BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            fi
            
            if [[ "$BRANCH_NAME" == "production" ]]; then
              echo "ENV=prod" >> $GITHUB_ENV
              echo "ENV=prod" >> $GITHUB_OUTPUT
            elif [[ "$BRANCH_NAME" == "main" ]]; then
              echo "ENV=QUALIF" >> $GITHUB_ENV
              echo "ENV=QUALIF" >> $GITHUB_OUTPUT
            elif [[ "$BRANCH_NAME" == feature/* ]]; then
              echo "ENV=QUALIF" >> $GITHUB_ENV
              echo "ENV=QUALIF" >> $GITHUB_OUTPUT
            else
              echo "ENV=UNKNOWN" >> $GITHUB_ENV
              echo "ENV=UNKNOWN" >> $GITHUB_OUTPUT
            fi
